"""Add notes

Revision ID: d0e6d3287299
Revises: 9ca722e1af37
Create Date: 2026-02-28 12:10:31.303516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e6d3287299'
down_revision: Union[str, None] = '9ca722e1af37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_folders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('folder_type', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['notes_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_folders_user_root', 'notes_folders', ['user_id'], unique=True, postgresql_where=sa.text("folder_type = 'root'"))
    op.create_index('idx_notes_folders_user_trash', 'notes_folders', ['user_id'], unique=True, postgresql_where=sa.text("folder_type = 'trash'"))
    op.create_index(op.f('ix_notes_folders_id'), 'notes_folders', ['id'], unique=False)
    op.create_index(op.f('ix_notes_folders_parent_id'), 'notes_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_notes_folders_user_id'), 'notes_folders', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['notes_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_folder_id'), 'notes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_folder_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_notes_folders_user_id'), table_name='notes_folders')
    op.drop_index(op.f('ix_notes_folders_parent_id'), table_name='notes_folders')
    op.drop_index(op.f('ix_notes_folders_id'), table_name='notes_folders')
    op.drop_index('idx_notes_folders_user_trash', table_name='notes_folders', postgresql_where=sa.text("folder_type = 'trash'"))
    op.drop_index('idx_notes_folders_user_root', table_name='notes_folders', postgresql_where=sa.text("folder_type = 'root'"))
    op.drop_table('notes_folders')
    # ### end Alembic commands ###
