"""add_notes_search_vector

Revision ID: 8bace0897ce7
Revises: ff5b1bbc5505
Create Date: 2026-07-16 16:32:57.960858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bace0897ce7'
down_revision: Union[str, None] = 'ff5b1bbc5505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('body_plain_text', sa.Text(), nullable=False, server_default=''))
    # Approximate backfill by stripping tags; exact extraction is applied going forward on create/update
    op.execute("UPDATE notes SET body_plain_text = regexp_replace(body, '<[^>]+>', ' ', 'g')")
    op.add_column('notes', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(body_plain_text, ''))", persisted=True), nullable=True))
    op.create_index('idx_notes_search_vector', 'notes', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notes_search_vector', table_name='notes', postgresql_using='gin')
    op.drop_column('notes', 'search_vector')
    op.drop_column('notes', 'body_plain_text')
    # ### end Alembic commands ###
